In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk
%matplotlib inline

In [2]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

Using Theano backend.


In [2]:
import trading as trd
from trading import State, SharpeRatio

In [85]:
# relaod module after modifying it
import importlib
importlib.reload(trd)
importlib.reload(trd.stock_history)
importlib.reload(trd.portfolio)
importlib.reload(trd.benchmarks)
importlib.reload(trd.environment)
importlib.reload(trd)

<module 'trading' from 'C:\\Users\\hamza\\Documents\\school\\cs_229\\cs229_final_project\\src\\trading\\__init__.py'>

## Formulate Problem

In [27]:
# number of inputs
n = State.num_states()
# number of outputs
k = trd.actions.size
# transaction cost to buy/sell a stock
trans_cost = 0.01
# sensitivity parameter for softmax
λ = 
# alpha / learning rate
α = 0.01

In [34]:
model = Sequential([
    Dense(input_dim=n, output_dim=100, init='uniform'),
    Activation('relu'),
    Dense(output_dim=100, init='uniform'),
    Activation('relu'),
    Dense(output_dim=k)])

# momentum in [0.5, 0.9, 0.95, 0.99]
# use Adam?
sgd = SGD(lr=α, decay=1e-6, momentum=0.5, nesterov=True)
model.compile(loss='mean_squared_error', optimizer=sgd, metrics=['accuracy'])

## Load Data

In [3]:
train, test = trd.get_stock_pairs(20)

In [4]:
pair = train[0]
lo = pair.hist_lo
hi = pair.hist_hi
assert(np.all(lo.index == hi.index))

T = len(lo.index)

for t in range(1, T):
    pass

In [73]:
m = State(pair, trans_cost=0)

In [96]:
len(lo)

1258

In [75]:
for _ in range(0, 16):
    m.step()

In [81]:
m.portfolio.iloc[1:17, :]

cash  cost_hi  cost_lo   num_hi   num_lo       total
2011-01-04  23.12    32.99    25.67  14645.0  19577.0   985703.26
2011-01-05  23.12    32.79    25.53  14645.0  19577.0   980033.48
2011-01-06  23.12    33.01    25.23  14645.0  19577.0   977382.28
2011-01-07  23.12    33.03    25.67  14645.0  19577.0   986289.06
2011-01-10  23.12    32.84    25.51  14645.0  19577.0   980374.19
2011-01-11  23.12    32.56    25.36  14645.0  19577.0   973337.04
2011-01-12  23.12    32.95    25.58  14645.0  19577.0   983355.53
2011-01-13  23.12    32.75    25.68  14645.0  19577.0   982384.23
2011-01-14  23.12    33.44    25.98  14645.0  19577.0   998362.38
2011-01-18  23.12    33.94    25.42  14645.0  19577.0   994721.76
2011-01-19  23.12    32.97    25.53  14645.0  19577.0   982669.58
2011-01-20  23.12    31.77    25.66  14645.0  19577.0   967640.59
2011-01-21  23.12    31.51    25.59  14645.0  19577.0   962462.50
2011-01-24  23.12    32.45    25.90  14645.0  19577.0   982297.67
2011-01-25  23.12    32.30    25.95  14645.0  19577.0   981079.77
2011-01-26  23.12    33.73    26.15  14645.0  19577.0  1005937.52

In [86]:
m.t

17

In [90]:
len(m.portfolio)

1258

In [65]:
xx = m.portfolio.ix[0:t,'total']
xx.values

array([ 1000000.  ,   985703.26,   980033.48,   977382.28,   986289.06,
         980374.19,   973337.04,   983355.53,   982384.23,   998362.38,
         994721.76,   982669.58,   967640.59,   962462.5 ,   982297.67,
         981079.77,  1005937.52])

In [70]:
t = m.t
x = m.portfolio.ix[0:t,'total'].values
x

array([ 1000000.  ,   985703.26,   980033.48,   977382.28,   986289.06,
         980374.19,   973337.04,   983355.53,   982384.23,   998362.38,
         994721.76,   982669.58,   967640.59,   962462.5 ,   982297.67,
         981079.77,  1005937.52])

In [71]:
x[1:t]-x[0:(t-1)]

array([-14296.74,  -5669.78,  -2651.2 ,   8906.78,  -5914.87,  -7037.15,
        10018.49,   -971.3 ,  15978.15,  -3640.62, -12052.18, -15028.99,
        -5178.09,  19835.17,  -1217.9 ,  24857.75])

In [ ]:
p = trd.make_portfolio(cost_lo=pair.hist_lo, cost_hi=pair.hist_hi)

In [53]:
#p[0,  = 
p.ix[0,['cash', 'num_lo', 'num_hi']]

cash  cost_hi  cost_lo  num_hi  num_lo  total
2011-01-03    18     8.28    34.69      34      12      0
2011-01-04     0     8.44    34.46       0       0      0
2011-01-05     0     8.54    34.57       0       0      0
2011-01-06     0     8.58    34.62       0       0      0
2011-01-07     0     8.64    34.48       0       0      0
2011-01-10     0     8.55    34.60       0       0      0
2011-01-11     0     8.72    34.55       0       0      0
2011-01-12     0     9.34    34.90       0       0      0
2011-01-13     0     9.63    34.92       0       0      0
2011-01-14     0     9.71    34.95       0       0      0
2011-01-18     0     9.66    35.08       0       0      0
2011-01-19     0     9.37    34.85       0       0      0
2011-01-20     0     9.60    35.25       0       0      0
2011-01-21     0     9.84    35.32       0       0      0
2011-01-24     0    10.05    35.06       0       0      0
2011-01-25     0     9.98    35.01       0       0      0
2011-01-26     0     9.95    35.06       0       0      0
2011-01-27     0    10.59    34.69       0       0      0
2011-01-28     0    10.37    34.45       0       0      0
2011-01-31     0    10.54    34.14       0       0      0
2011-02-01     0    10.81    34.30       0       0      0
2011-02-02     0    10.89    34.38       0       0      0
2011-02-03     0    10.90    34.47       0       0      0
2011-02-04     0    11.05    34.42       0       0      0
2011-02-07     0    11.29    34.23       0       0      0
2011-02-08     0    11.44    34.34       0       0      0
2011-02-09     0    11.26    34.52       0       0      0
2011-02-10     0    11.31    34.29       0       0      0
2011-02-11     0    11.32    34.43       0       0      0
2011-02-14     0    11.65    34.48       0       0      0
...          ...      ...      ...     ...     ...    ...
2015-11-18     0    15.61    49.04       0       0      0
2015-11-19     0    15.87    49.47       0       0      0
2015-11-20     0    15.43    48.82       0       0      0
2015-11-23     0    15.32    49.79       0       0      0
2015-11-24     0    15.63    51.33       0       0      0
2015-11-25     0    15.58    52.52       0       0      0
2015-11-27     0    15.56    53.10       0       0      0
2015-11-30     0    15.93    52.24       0       0      0
2015-12-01     0    16.55    52.81       0       0      0
2015-12-02     0    15.82    52.69       0       0      0
2015-12-03     0    15.61    52.44       0       0      0
2015-12-04     0    15.50    53.12       0       0      0
2015-12-07     0    14.85    53.12       0       0      0
2015-12-08     0    14.60    53.49       0       0      0
2015-12-09     0    14.32    53.53       0       0      0
2015-12-10     0    14.66    53.64       0       0      0
2015-12-11     0    14.04    52.99       0       0      0
2015-12-14     0    13.66    53.25       0       0      0
2015-12-15     0    14.18    53.21       0       0      0
2015-12-16     0    14.07    53.72       0       0      0
2015-12-17     0    14.32    53.14       0       0      0
2015-12-18     0    14.36    52.21       0       0      0
2015-12-21     0    14.77    52.66       0       0      0
2015-12-22     0    14.61    53.15       0       0      0
2015-12-23     0    14.30    53.57       0       0      0
2015-12-24     0    14.48    53.32       0       0      0
2015-12-28     0    14.19    53.59       0       0      0
2015-12-29     0    14.34    53.68       0       0      0
2015-12-30     0    14.16    53.21       0       0      0
2015-12-31     0    14.16    52.55       0       0      0

[1258 rows x 6 columns]

In [9]:
model.fit(data, y, nb_epoch=10, batch_size=32)

Epoch 1/10
1000/1000 [==============================] - 0s - loss: 31.0667 - acc: 0.3550     
Epoch 2/10
1000/1000 [==============================] - 0s - loss: 22.0609 - acc: 0.3470     
Epoch 3/10
1000/1000 [==============================] - 0s - loss: 22.2079 - acc: 0.3350     
Epoch 4/10
1000/1000 [==============================] - 0s - loss: 21.9613 - acc: 0.3360     
Epoch 5/10
1000/1000 [==============================] - 0s - loss: 21.9638 - acc: 0.3250     
Epoch 6/10
1000/1000 [==============================] - 0s - loss: 21.8397 - acc: 0.3230     
Epoch 7/10
1000/1000 [==============================] - 0s - loss: 21.7023 - acc: 0.3810     
Epoch 8/10
1000/1000 [==============================] - 0s - loss: 21.6407 - acc: 0.3670     
Epoch 9/10
1000/1000 [==============================] - 0s - loss: 21.6806 - acc: 0.3440     
Epoch 10/10
1000/1000 [==============================] - 0s - loss: 21.6966 - acc: 0.3340     


In [12]:
model.predict(np.random.rand(2, n))

array([[ 7.62245607,  7.38628244,  7.45234728],
       [ 8.50828552,  8.19099331,  8.26092625]], dtype=float32)